"""
International Textile Construction & Weave Yarn Engineering Matrix.
Contains 150+ textile engineering specifications with warp/weft yarn counts,
tensile ratings, finishing treatments, and international trade tariff classifications.
"""

from typing import Dict, List, Optional, Any
from pydantic import BaseModel

class YarnStructureSpec(BaseModel):
    fabric_id: str
    commercial_trade_name: str
    fiber_blend_ratio: str
    warp_yarn_count: str
    weft_yarn_count: str
    ends_per_inch: int
    picks_per_inch: int
    weight_gsm: float
    finishing_processes: List[str]
    tensile_strength_warp_n: float
    tensile_strength_weft_n: float
    air_permeability_cm3_per_s: float
    hsn_tax_tariff: str = "6205"

INTERNATIONAL_FABRIC_MATRIX: Dict[str, YarnStructureSpec] = {
    "FAB_SPEC_0001": YarnStructureSpec(
        fabric_id="FAB_SPEC_0001",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-1",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=59,
        picks_per_inch=53,
        weight_gsm=166.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=522.5,
        tensile_strength_weft_n=482.0,
        air_permeability_cm3_per_s=311.0
    ),
    "FAB_SPEC_0002": YarnStructureSpec(
        fabric_id="FAB_SPEC_0002",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-2",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=122,
        picks_per_inch=97,
        weight_gsm=84.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=285.0,
        tensile_strength_weft_n=244.0,
        air_permeability_cm3_per_s=192.0
    ),
    "FAB_SPEC_0003": YarnStructureSpec(
        fabric_id="FAB_SPEC_0003",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-3",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=71,
        picks_per_inch=47,
        weight_gsm=493.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1257.5,
        tensile_strength_weft_n=986.0,
        air_permeability_cm3_per_s=48.0
    ),
    "FAB_SPEC_0004": YarnStructureSpec(
        fabric_id="FAB_SPEC_0004",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-4",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=132,
        picks_per_inch=92,
        weight_gsm=194.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=630.0,
        tensile_strength_weft_n=548.0,
        air_permeability_cm3_per_s=214.0
    ),
    "FAB_SPEC_0005": YarnStructureSpec(
        fabric_id="FAB_SPEC_0005",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-5",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=145,
        picks_per_inch=115,
        weight_gsm=245.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=592.5,
        tensile_strength_weft_n=430.0,
        air_permeability_cm3_per_s=90.0
    ),
    "FAB_SPEC_0006": YarnStructureSpec(
        fabric_id="FAB_SPEC_0006",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-6",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=34,
        picks_per_inch=38,
        weight_gsm=226.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=225.0,
        tensile_strength_weft_n=202.0,
        air_permeability_cm3_per_s=386.0
    ),
    "FAB_SPEC_0007": YarnStructureSpec(
        fabric_id="FAB_SPEC_0007",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-7",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=49,
        picks_per_inch=45,
        weight_gsm=457.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=907.5,
        tensile_strength_weft_n=794.0,
        air_permeability_cm3_per_s=127.0
    ),
    "FAB_SPEC_0008": YarnStructureSpec(
        fabric_id="FAB_SPEC_0008",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-8",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=168,
        picks_per_inch=128,
        weight_gsm=126.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=470.0,
        tensile_strength_weft_n=396.0,
        air_permeability_cm3_per_s=148.0
    ),
    "FAB_SPEC_0009": YarnStructureSpec(
        fabric_id="FAB_SPEC_0009",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-9",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=67,
        picks_per_inch=61,
        weight_gsm=174.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=542.5,
        tensile_strength_weft_n=498.0,
        air_permeability_cm3_per_s=319.0
    ),
    "FAB_SPEC_0010": YarnStructureSpec(
        fabric_id="FAB_SPEC_0010",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-10",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=130,
        picks_per_inch=105,
        weight_gsm=92.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=305.0,
        tensile_strength_weft_n=260.0,
        air_permeability_cm3_per_s=200.0
    ),
    "FAB_SPEC_0011": YarnStructureSpec(
        fabric_id="FAB_SPEC_0011",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-11",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=79,
        picks_per_inch=55,
        weight_gsm=501.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1277.5,
        tensile_strength_weft_n=1002.0,
        air_permeability_cm3_per_s=56.0
    ),
    "FAB_SPEC_0012": YarnStructureSpec(
        fabric_id="FAB_SPEC_0012",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-12",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=140,
        picks_per_inch=100,
        weight_gsm=202.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=650.0,
        tensile_strength_weft_n=564.0,
        air_permeability_cm3_per_s=222.0
    ),
    "FAB_SPEC_0013": YarnStructureSpec(
        fabric_id="FAB_SPEC_0013",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-13",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=153,
        picks_per_inch=123,
        weight_gsm=253.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=612.5,
        tensile_strength_weft_n=446.0,
        air_permeability_cm3_per_s=98.0
    ),
    "FAB_SPEC_0014": YarnStructureSpec(
        fabric_id="FAB_SPEC_0014",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-14",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=42,
        picks_per_inch=46,
        weight_gsm=234.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=245.0,
        tensile_strength_weft_n=218.0,
        air_permeability_cm3_per_s=394.0
    ),
    "FAB_SPEC_0015": YarnStructureSpec(
        fabric_id="FAB_SPEC_0015",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-15",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=57,
        picks_per_inch=38,
        weight_gsm=465.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=927.5,
        tensile_strength_weft_n=810.0,
        air_permeability_cm3_per_s=135.0
    ),
    "FAB_SPEC_0016": YarnStructureSpec(
        fabric_id="FAB_SPEC_0016",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-16",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=176,
        picks_per_inch=121,
        weight_gsm=134.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=490.0,
        tensile_strength_weft_n=412.0,
        air_permeability_cm3_per_s=156.0
    ),
    "FAB_SPEC_0017": YarnStructureSpec(
        fabric_id="FAB_SPEC_0017",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-17",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=75,
        picks_per_inch=54,
        weight_gsm=182.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=562.5,
        tensile_strength_weft_n=514.0,
        air_permeability_cm3_per_s=327.0
    ),
    "FAB_SPEC_0018": YarnStructureSpec(
        fabric_id="FAB_SPEC_0018",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-18",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=138,
        picks_per_inch=98,
        weight_gsm=100.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=325.0,
        tensile_strength_weft_n=276.0,
        air_permeability_cm3_per_s=208.0
    ),
    "FAB_SPEC_0019": YarnStructureSpec(
        fabric_id="FAB_SPEC_0019",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-19",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=87,
        picks_per_inch=48,
        weight_gsm=509.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1297.5,
        tensile_strength_weft_n=1018.0,
        air_permeability_cm3_per_s=64.0
    ),
    "FAB_SPEC_0020": YarnStructureSpec(
        fabric_id="FAB_SPEC_0020",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-20",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=128,
        picks_per_inch=93,
        weight_gsm=210.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=670.0,
        tensile_strength_weft_n=580.0,
        air_permeability_cm3_per_s=230.0
    ),
    "FAB_SPEC_0021": YarnStructureSpec(
        fabric_id="FAB_SPEC_0021",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-21",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=141,
        picks_per_inch=116,
        weight_gsm=261.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=632.5,
        tensile_strength_weft_n=462.0,
        air_permeability_cm3_per_s=106.0
    ),
    "FAB_SPEC_0022": YarnStructureSpec(
        fabric_id="FAB_SPEC_0022",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-22",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=30,
        picks_per_inch=39,
        weight_gsm=242.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=265.0,
        tensile_strength_weft_n=234.0,
        air_permeability_cm3_per_s=402.0
    ),
    "FAB_SPEC_0023": YarnStructureSpec(
        fabric_id="FAB_SPEC_0023",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-23",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=45,
        picks_per_inch=46,
        weight_gsm=473.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=947.5,
        tensile_strength_weft_n=826.0,
        air_permeability_cm3_per_s=143.0
    ),
    "FAB_SPEC_0024": YarnStructureSpec(
        fabric_id="FAB_SPEC_0024",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-24",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=164,
        picks_per_inch=129,
        weight_gsm=142.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=510.0,
        tensile_strength_weft_n=428.0,
        air_permeability_cm3_per_s=164.0
    ),
    "FAB_SPEC_0025": YarnStructureSpec(
        fabric_id="FAB_SPEC_0025",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-25",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=63,
        picks_per_inch=62,
        weight_gsm=190.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=582.5,
        tensile_strength_weft_n=530.0,
        air_permeability_cm3_per_s=335.0
    ),
    "FAB_SPEC_0026": YarnStructureSpec(
        fabric_id="FAB_SPEC_0026",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-26",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=126,
        picks_per_inch=106,
        weight_gsm=108.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=345.0,
        tensile_strength_weft_n=292.0,
        air_permeability_cm3_per_s=216.0
    ),
    "FAB_SPEC_0027": YarnStructureSpec(
        fabric_id="FAB_SPEC_0027",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-27",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=75,
        picks_per_inch=56,
        weight_gsm=517.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1317.5,
        tensile_strength_weft_n=1034.0,
        air_permeability_cm3_per_s=72.0
    ),
    "FAB_SPEC_0028": YarnStructureSpec(
        fabric_id="FAB_SPEC_0028",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-28",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=136,
        picks_per_inch=101,
        weight_gsm=218.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=690.0,
        tensile_strength_weft_n=596.0,
        air_permeability_cm3_per_s=238.0
    ),
    "FAB_SPEC_0029": YarnStructureSpec(
        fabric_id="FAB_SPEC_0029",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-29",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=149,
        picks_per_inch=124,
        weight_gsm=269.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=652.5,
        tensile_strength_weft_n=478.0,
        air_permeability_cm3_per_s=114.0
    ),
    "FAB_SPEC_0030": YarnStructureSpec(
        fabric_id="FAB_SPEC_0030",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-30",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=38,
        picks_per_inch=32,
        weight_gsm=220.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=285.0,
        tensile_strength_weft_n=250.0,
        air_permeability_cm3_per_s=410.0
    ),
    "FAB_SPEC_0031": YarnStructureSpec(
        fabric_id="FAB_SPEC_0031",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-31",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=53,
        picks_per_inch=39,
        weight_gsm=451.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=967.5,
        tensile_strength_weft_n=842.0,
        air_permeability_cm3_per_s=151.0
    ),
    "FAB_SPEC_0032": YarnStructureSpec(
        fabric_id="FAB_SPEC_0032",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-32",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=172,
        picks_per_inch=122,
        weight_gsm=120.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=530.0,
        tensile_strength_weft_n=444.0,
        air_permeability_cm3_per_s=172.0
    ),
    "FAB_SPEC_0033": YarnStructureSpec(
        fabric_id="FAB_SPEC_0033",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-33",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=71,
        picks_per_inch=55,
        weight_gsm=168.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=602.5,
        tensile_strength_weft_n=546.0,
        air_permeability_cm3_per_s=343.0
    ),
    "FAB_SPEC_0034": YarnStructureSpec(
        fabric_id="FAB_SPEC_0034",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-34",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=134,
        picks_per_inch=99,
        weight_gsm=86.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=365.0,
        tensile_strength_weft_n=308.0,
        air_permeability_cm3_per_s=224.0
    ),
    "FAB_SPEC_0035": YarnStructureSpec(
        fabric_id="FAB_SPEC_0035",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-35",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=83,
        picks_per_inch=49,
        weight_gsm=495.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1337.5,
        tensile_strength_weft_n=1050.0,
        air_permeability_cm3_per_s=80.0
    ),
    "FAB_SPEC_0036": YarnStructureSpec(
        fabric_id="FAB_SPEC_0036",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-36",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=144,
        picks_per_inch=94,
        weight_gsm=196.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=710.0,
        tensile_strength_weft_n=612.0,
        air_permeability_cm3_per_s=246.0
    ),
    "FAB_SPEC_0037": YarnStructureSpec(
        fabric_id="FAB_SPEC_0037",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-37",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=157,
        picks_per_inch=117,
        weight_gsm=247.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=672.5,
        tensile_strength_weft_n=494.0,
        air_permeability_cm3_per_s=122.0
    ),
    "FAB_SPEC_0038": YarnStructureSpec(
        fabric_id="FAB_SPEC_0038",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-38",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=46,
        picks_per_inch=40,
        weight_gsm=228.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=305.0,
        tensile_strength_weft_n=266.0,
        air_permeability_cm3_per_s=418.0
    ),
    "FAB_SPEC_0039": YarnStructureSpec(
        fabric_id="FAB_SPEC_0039",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-39",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=61,
        picks_per_inch=47,
        weight_gsm=459.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=987.5,
        tensile_strength_weft_n=858.0,
        air_permeability_cm3_per_s=159.0
    ),
    "FAB_SPEC_0040": YarnStructureSpec(
        fabric_id="FAB_SPEC_0040",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-40",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=160,
        picks_per_inch=130,
        weight_gsm=128.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=550.0,
        tensile_strength_weft_n=460.0,
        air_permeability_cm3_per_s=140.0
    ),
    "FAB_SPEC_0041": YarnStructureSpec(
        fabric_id="FAB_SPEC_0041",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-41",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=59,
        picks_per_inch=63,
        weight_gsm=176.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=622.5,
        tensile_strength_weft_n=562.0,
        air_permeability_cm3_per_s=311.0
    ),
    "FAB_SPEC_0042": YarnStructureSpec(
        fabric_id="FAB_SPEC_0042",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-42",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=122,
        picks_per_inch=107,
        weight_gsm=94.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=385.0,
        tensile_strength_weft_n=324.0,
        air_permeability_cm3_per_s=192.0
    ),
    "FAB_SPEC_0043": YarnStructureSpec(
        fabric_id="FAB_SPEC_0043",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-43",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=71,
        picks_per_inch=57,
        weight_gsm=503.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1357.5,
        tensile_strength_weft_n=1066.0,
        air_permeability_cm3_per_s=48.0
    ),
    "FAB_SPEC_0044": YarnStructureSpec(
        fabric_id="FAB_SPEC_0044",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-44",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=132,
        picks_per_inch=102,
        weight_gsm=204.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=730.0,
        tensile_strength_weft_n=628.0,
        air_permeability_cm3_per_s=214.0
    ),
    "FAB_SPEC_0045": YarnStructureSpec(
        fabric_id="FAB_SPEC_0045",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-45",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=145,
        picks_per_inch=110,
        weight_gsm=255.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=692.5,
        tensile_strength_weft_n=510.0,
        air_permeability_cm3_per_s=90.0
    ),
    "FAB_SPEC_0046": YarnStructureSpec(
        fabric_id="FAB_SPEC_0046",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-46",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=34,
        picks_per_inch=33,
        weight_gsm=236.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=325.0,
        tensile_strength_weft_n=282.0,
        air_permeability_cm3_per_s=386.0
    ),
    "FAB_SPEC_0047": YarnStructureSpec(
        fabric_id="FAB_SPEC_0047",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-47",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=49,
        picks_per_inch=40,
        weight_gsm=467.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1007.5,
        tensile_strength_weft_n=874.0,
        air_permeability_cm3_per_s=127.0
    ),
    "FAB_SPEC_0048": YarnStructureSpec(
        fabric_id="FAB_SPEC_0048",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-48",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=168,
        picks_per_inch=123,
        weight_gsm=136.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=570.0,
        tensile_strength_weft_n=476.0,
        air_permeability_cm3_per_s=148.0
    ),
    "FAB_SPEC_0049": YarnStructureSpec(
        fabric_id="FAB_SPEC_0049",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-49",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=67,
        picks_per_inch=56,
        weight_gsm=184.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=642.5,
        tensile_strength_weft_n=578.0,
        air_permeability_cm3_per_s=319.0
    ),
    "FAB_SPEC_0050": YarnStructureSpec(
        fabric_id="FAB_SPEC_0050",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-50",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=130,
        picks_per_inch=100,
        weight_gsm=102.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=405.0,
        tensile_strength_weft_n=340.0,
        air_permeability_cm3_per_s=200.0
    ),
    "FAB_SPEC_0051": YarnStructureSpec(
        fabric_id="FAB_SPEC_0051",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-51",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=79,
        picks_per_inch=50,
        weight_gsm=511.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1377.5,
        tensile_strength_weft_n=1082.0,
        air_permeability_cm3_per_s=56.0
    ),
    "FAB_SPEC_0052": YarnStructureSpec(
        fabric_id="FAB_SPEC_0052",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-52",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=140,
        picks_per_inch=95,
        weight_gsm=212.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=750.0,
        tensile_strength_weft_n=644.0,
        air_permeability_cm3_per_s=222.0
    ),
    "FAB_SPEC_0053": YarnStructureSpec(
        fabric_id="FAB_SPEC_0053",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-53",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=153,
        picks_per_inch=118,
        weight_gsm=263.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=712.5,
        tensile_strength_weft_n=526.0,
        air_permeability_cm3_per_s=98.0
    ),
    "FAB_SPEC_0054": YarnStructureSpec(
        fabric_id="FAB_SPEC_0054",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-54",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=42,
        picks_per_inch=41,
        weight_gsm=244.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=345.0,
        tensile_strength_weft_n=298.0,
        air_permeability_cm3_per_s=394.0
    ),
    "FAB_SPEC_0055": YarnStructureSpec(
        fabric_id="FAB_SPEC_0055",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-55",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=57,
        picks_per_inch=48,
        weight_gsm=475.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1027.5,
        tensile_strength_weft_n=890.0,
        air_permeability_cm3_per_s=135.0
    ),
    "FAB_SPEC_0056": YarnStructureSpec(
        fabric_id="FAB_SPEC_0056",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-56",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=176,
        picks_per_inch=131,
        weight_gsm=144.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=590.0,
        tensile_strength_weft_n=492.0,
        air_permeability_cm3_per_s=156.0
    ),
    "FAB_SPEC_0057": YarnStructureSpec(
        fabric_id="FAB_SPEC_0057",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-57",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=75,
        picks_per_inch=64,
        weight_gsm=192.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=662.5,
        tensile_strength_weft_n=594.0,
        air_permeability_cm3_per_s=327.0
    ),
    "FAB_SPEC_0058": YarnStructureSpec(
        fabric_id="FAB_SPEC_0058",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-58",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=138,
        picks_per_inch=108,
        weight_gsm=110.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=425.0,
        tensile_strength_weft_n=356.0,
        air_permeability_cm3_per_s=208.0
    ),
    "FAB_SPEC_0059": YarnStructureSpec(
        fabric_id="FAB_SPEC_0059",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-59",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=87,
        picks_per_inch=58,
        weight_gsm=519.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1397.5,
        tensile_strength_weft_n=1098.0,
        air_permeability_cm3_per_s=64.0
    ),
    "FAB_SPEC_0060": YarnStructureSpec(
        fabric_id="FAB_SPEC_0060",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-60",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=128,
        picks_per_inch=88,
        weight_gsm=190.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=770.0,
        tensile_strength_weft_n=660.0,
        air_permeability_cm3_per_s=230.0
    ),
    "FAB_SPEC_0061": YarnStructureSpec(
        fabric_id="FAB_SPEC_0061",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-61",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=141,
        picks_per_inch=111,
        weight_gsm=241.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=732.5,
        tensile_strength_weft_n=542.0,
        air_permeability_cm3_per_s=106.0
    ),
    "FAB_SPEC_0062": YarnStructureSpec(
        fabric_id="FAB_SPEC_0062",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-62",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=30,
        picks_per_inch=34,
        weight_gsm=222.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=365.0,
        tensile_strength_weft_n=314.0,
        air_permeability_cm3_per_s=402.0
    ),
    "FAB_SPEC_0063": YarnStructureSpec(
        fabric_id="FAB_SPEC_0063",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-63",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=45,
        picks_per_inch=41,
        weight_gsm=453.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1047.5,
        tensile_strength_weft_n=906.0,
        air_permeability_cm3_per_s=143.0
    ),
    "FAB_SPEC_0064": YarnStructureSpec(
        fabric_id="FAB_SPEC_0064",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-64",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=164,
        picks_per_inch=124,
        weight_gsm=122.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=610.0,
        tensile_strength_weft_n=508.0,
        air_permeability_cm3_per_s=164.0
    ),
    "FAB_SPEC_0065": YarnStructureSpec(
        fabric_id="FAB_SPEC_0065",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-65",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=63,
        picks_per_inch=57,
        weight_gsm=170.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=682.5,
        tensile_strength_weft_n=610.0,
        air_permeability_cm3_per_s=335.0
    ),
    "FAB_SPEC_0066": YarnStructureSpec(
        fabric_id="FAB_SPEC_0066",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-66",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=126,
        picks_per_inch=101,
        weight_gsm=88.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=445.0,
        tensile_strength_weft_n=372.0,
        air_permeability_cm3_per_s=216.0
    ),
    "FAB_SPEC_0067": YarnStructureSpec(
        fabric_id="FAB_SPEC_0067",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-67",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=75,
        picks_per_inch=51,
        weight_gsm=497.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1417.5,
        tensile_strength_weft_n=1114.0,
        air_permeability_cm3_per_s=72.0
    ),
    "FAB_SPEC_0068": YarnStructureSpec(
        fabric_id="FAB_SPEC_0068",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-68",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=136,
        picks_per_inch=96,
        weight_gsm=198.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=790.0,
        tensile_strength_weft_n=676.0,
        air_permeability_cm3_per_s=238.0
    ),
    "FAB_SPEC_0069": YarnStructureSpec(
        fabric_id="FAB_SPEC_0069",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-69",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=149,
        picks_per_inch=119,
        weight_gsm=249.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=752.5,
        tensile_strength_weft_n=558.0,
        air_permeability_cm3_per_s=114.0
    ),
    "FAB_SPEC_0070": YarnStructureSpec(
        fabric_id="FAB_SPEC_0070",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-70",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=38,
        picks_per_inch=42,
        weight_gsm=230.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=385.0,
        tensile_strength_weft_n=330.0,
        air_permeability_cm3_per_s=410.0
    ),
    "FAB_SPEC_0071": YarnStructureSpec(
        fabric_id="FAB_SPEC_0071",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-71",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=53,
        picks_per_inch=49,
        weight_gsm=461.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1067.5,
        tensile_strength_weft_n=922.0,
        air_permeability_cm3_per_s=151.0
    ),
    "FAB_SPEC_0072": YarnStructureSpec(
        fabric_id="FAB_SPEC_0072",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-72",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=172,
        picks_per_inch=132,
        weight_gsm=130.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=630.0,
        tensile_strength_weft_n=524.0,
        air_permeability_cm3_per_s=172.0
    ),
    "FAB_SPEC_0073": YarnStructureSpec(
        fabric_id="FAB_SPEC_0073",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-73",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=71,
        picks_per_inch=65,
        weight_gsm=178.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=702.5,
        tensile_strength_weft_n=626.0,
        air_permeability_cm3_per_s=343.0
    ),
    "FAB_SPEC_0074": YarnStructureSpec(
        fabric_id="FAB_SPEC_0074",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-74",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=134,
        picks_per_inch=109,
        weight_gsm=96.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=465.0,
        tensile_strength_weft_n=388.0,
        air_permeability_cm3_per_s=224.0
    ),
    "FAB_SPEC_0075": YarnStructureSpec(
        fabric_id="FAB_SPEC_0075",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-75",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=83,
        picks_per_inch=44,
        weight_gsm=505.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1437.5,
        tensile_strength_weft_n=1130.0,
        air_permeability_cm3_per_s=80.0
    ),
    "FAB_SPEC_0076": YarnStructureSpec(
        fabric_id="FAB_SPEC_0076",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-76",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=144,
        picks_per_inch=89,
        weight_gsm=206.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=810.0,
        tensile_strength_weft_n=692.0,
        air_permeability_cm3_per_s=246.0
    ),
    "FAB_SPEC_0077": YarnStructureSpec(
        fabric_id="FAB_SPEC_0077",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-77",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=157,
        picks_per_inch=112,
        weight_gsm=257.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=772.5,
        tensile_strength_weft_n=574.0,
        air_permeability_cm3_per_s=122.0
    ),
    "FAB_SPEC_0078": YarnStructureSpec(
        fabric_id="FAB_SPEC_0078",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-78",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=46,
        picks_per_inch=35,
        weight_gsm=238.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=405.0,
        tensile_strength_weft_n=346.0,
        air_permeability_cm3_per_s=418.0
    ),
    "FAB_SPEC_0079": YarnStructureSpec(
        fabric_id="FAB_SPEC_0079",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-79",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=61,
        picks_per_inch=42,
        weight_gsm=469.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1087.5,
        tensile_strength_weft_n=938.0,
        air_permeability_cm3_per_s=159.0
    ),
    "FAB_SPEC_0080": YarnStructureSpec(
        fabric_id="FAB_SPEC_0080",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-80",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=160,
        picks_per_inch=125,
        weight_gsm=138.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=650.0,
        tensile_strength_weft_n=540.0,
        air_permeability_cm3_per_s=140.0
    ),
    "FAB_SPEC_0081": YarnStructureSpec(
        fabric_id="FAB_SPEC_0081",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-81",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=59,
        picks_per_inch=58,
        weight_gsm=186.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=722.5,
        tensile_strength_weft_n=642.0,
        air_permeability_cm3_per_s=311.0
    ),
    "FAB_SPEC_0082": YarnStructureSpec(
        fabric_id="FAB_SPEC_0082",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-82",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=122,
        picks_per_inch=102,
        weight_gsm=104.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=485.0,
        tensile_strength_weft_n=404.0,
        air_permeability_cm3_per_s=192.0
    ),
    "FAB_SPEC_0083": YarnStructureSpec(
        fabric_id="FAB_SPEC_0083",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-83",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=71,
        picks_per_inch=52,
        weight_gsm=513.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1457.5,
        tensile_strength_weft_n=1146.0,
        air_permeability_cm3_per_s=48.0
    ),
    "FAB_SPEC_0084": YarnStructureSpec(
        fabric_id="FAB_SPEC_0084",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-84",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=132,
        picks_per_inch=97,
        weight_gsm=214.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=830.0,
        tensile_strength_weft_n=708.0,
        air_permeability_cm3_per_s=214.0
    ),
    "FAB_SPEC_0085": YarnStructureSpec(
        fabric_id="FAB_SPEC_0085",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-85",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=145,
        picks_per_inch=120,
        weight_gsm=265.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=792.5,
        tensile_strength_weft_n=590.0,
        air_permeability_cm3_per_s=90.0
    ),
    "FAB_SPEC_0086": YarnStructureSpec(
        fabric_id="FAB_SPEC_0086",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-86",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=34,
        picks_per_inch=43,
        weight_gsm=246.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=425.0,
        tensile_strength_weft_n=362.0,
        air_permeability_cm3_per_s=386.0
    ),
    "FAB_SPEC_0087": YarnStructureSpec(
        fabric_id="FAB_SPEC_0087",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-87",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=49,
        picks_per_inch=50,
        weight_gsm=477.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1107.5,
        tensile_strength_weft_n=954.0,
        air_permeability_cm3_per_s=127.0
    ),
    "FAB_SPEC_0088": YarnStructureSpec(
        fabric_id="FAB_SPEC_0088",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-88",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=168,
        picks_per_inch=133,
        weight_gsm=146.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=670.0,
        tensile_strength_weft_n=556.0,
        air_permeability_cm3_per_s=148.0
    ),
    "FAB_SPEC_0089": YarnStructureSpec(
        fabric_id="FAB_SPEC_0089",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-89",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=67,
        picks_per_inch=66,
        weight_gsm=194.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=742.5,
        tensile_strength_weft_n=658.0,
        air_permeability_cm3_per_s=319.0
    ),
    "FAB_SPEC_0090": YarnStructureSpec(
        fabric_id="FAB_SPEC_0090",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-90",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=130,
        picks_per_inch=95,
        weight_gsm=82.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=505.0,
        tensile_strength_weft_n=420.0,
        air_permeability_cm3_per_s=200.0
    ),
    "FAB_SPEC_0091": YarnStructureSpec(
        fabric_id="FAB_SPEC_0091",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-91",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=79,
        picks_per_inch=45,
        weight_gsm=491.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1477.5,
        tensile_strength_weft_n=1162.0,
        air_permeability_cm3_per_s=56.0
    ),
    "FAB_SPEC_0092": YarnStructureSpec(
        fabric_id="FAB_SPEC_0092",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-92",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=140,
        picks_per_inch=90,
        weight_gsm=192.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=850.0,
        tensile_strength_weft_n=724.0,
        air_permeability_cm3_per_s=222.0
    ),
    "FAB_SPEC_0093": YarnStructureSpec(
        fabric_id="FAB_SPEC_0093",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-93",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=153,
        picks_per_inch=113,
        weight_gsm=243.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=812.5,
        tensile_strength_weft_n=606.0,
        air_permeability_cm3_per_s=98.0
    ),
    "FAB_SPEC_0094": YarnStructureSpec(
        fabric_id="FAB_SPEC_0094",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-94",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=42,
        picks_per_inch=36,
        weight_gsm=224.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=445.0,
        tensile_strength_weft_n=378.0,
        air_permeability_cm3_per_s=394.0
    ),
    "FAB_SPEC_0095": YarnStructureSpec(
        fabric_id="FAB_SPEC_0095",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-95",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=57,
        picks_per_inch=43,
        weight_gsm=455.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1127.5,
        tensile_strength_weft_n=970.0,
        air_permeability_cm3_per_s=135.0
    ),
    "FAB_SPEC_0096": YarnStructureSpec(
        fabric_id="FAB_SPEC_0096",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-96",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=176,
        picks_per_inch=126,
        weight_gsm=124.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=690.0,
        tensile_strength_weft_n=572.0,
        air_permeability_cm3_per_s=156.0
    ),
    "FAB_SPEC_0097": YarnStructureSpec(
        fabric_id="FAB_SPEC_0097",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-97",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=75,
        picks_per_inch=59,
        weight_gsm=172.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=762.5,
        tensile_strength_weft_n=674.0,
        air_permeability_cm3_per_s=327.0
    ),
    "FAB_SPEC_0098": YarnStructureSpec(
        fabric_id="FAB_SPEC_0098",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-98",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=138,
        picks_per_inch=103,
        weight_gsm=90.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=525.0,
        tensile_strength_weft_n=436.0,
        air_permeability_cm3_per_s=208.0
    ),
    "FAB_SPEC_0099": YarnStructureSpec(
        fabric_id="FAB_SPEC_0099",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-99",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=87,
        picks_per_inch=53,
        weight_gsm=499.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1497.5,
        tensile_strength_weft_n=1178.0,
        air_permeability_cm3_per_s=64.0
    ),
    "FAB_SPEC_0100": YarnStructureSpec(
        fabric_id="FAB_SPEC_0100",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-100",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=128,
        picks_per_inch=98,
        weight_gsm=200.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=870.0,
        tensile_strength_weft_n=740.0,
        air_permeability_cm3_per_s=230.0
    ),
    "FAB_SPEC_0101": YarnStructureSpec(
        fabric_id="FAB_SPEC_0101",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-101",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=141,
        picks_per_inch=121,
        weight_gsm=251.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=832.5,
        tensile_strength_weft_n=622.0,
        air_permeability_cm3_per_s=106.0
    ),
    "FAB_SPEC_0102": YarnStructureSpec(
        fabric_id="FAB_SPEC_0102",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-102",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=30,
        picks_per_inch=44,
        weight_gsm=232.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=465.0,
        tensile_strength_weft_n=394.0,
        air_permeability_cm3_per_s=402.0
    ),
    "FAB_SPEC_0103": YarnStructureSpec(
        fabric_id="FAB_SPEC_0103",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-103",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=45,
        picks_per_inch=51,
        weight_gsm=463.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1147.5,
        tensile_strength_weft_n=986.0,
        air_permeability_cm3_per_s=143.0
    ),
    "FAB_SPEC_0104": YarnStructureSpec(
        fabric_id="FAB_SPEC_0104",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-104",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=164,
        picks_per_inch=134,
        weight_gsm=132.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=710.0,
        tensile_strength_weft_n=588.0,
        air_permeability_cm3_per_s=164.0
    ),
    "FAB_SPEC_0105": YarnStructureSpec(
        fabric_id="FAB_SPEC_0105",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-105",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=63,
        picks_per_inch=52,
        weight_gsm=180.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=782.5,
        tensile_strength_weft_n=690.0,
        air_permeability_cm3_per_s=335.0
    ),
    "FAB_SPEC_0106": YarnStructureSpec(
        fabric_id="FAB_SPEC_0106",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-106",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=126,
        picks_per_inch=96,
        weight_gsm=98.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=545.0,
        tensile_strength_weft_n=452.0,
        air_permeability_cm3_per_s=216.0
    ),
    "FAB_SPEC_0107": YarnStructureSpec(
        fabric_id="FAB_SPEC_0107",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-107",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=75,
        picks_per_inch=46,
        weight_gsm=507.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1517.5,
        tensile_strength_weft_n=1194.0,
        air_permeability_cm3_per_s=72.0
    ),
    "FAB_SPEC_0108": YarnStructureSpec(
        fabric_id="FAB_SPEC_0108",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-108",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=136,
        picks_per_inch=91,
        weight_gsm=208.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=890.0,
        tensile_strength_weft_n=756.0,
        air_permeability_cm3_per_s=238.0
    ),
    "FAB_SPEC_0109": YarnStructureSpec(
        fabric_id="FAB_SPEC_0109",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-109",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=149,
        picks_per_inch=114,
        weight_gsm=259.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=852.5,
        tensile_strength_weft_n=638.0,
        air_permeability_cm3_per_s=114.0
    ),
    "FAB_SPEC_0110": YarnStructureSpec(
        fabric_id="FAB_SPEC_0110",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-110",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=38,
        picks_per_inch=37,
        weight_gsm=240.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=485.0,
        tensile_strength_weft_n=410.0,
        air_permeability_cm3_per_s=410.0
    ),
    "FAB_SPEC_0111": YarnStructureSpec(
        fabric_id="FAB_SPEC_0111",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-111",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=53,
        picks_per_inch=44,
        weight_gsm=471.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1167.5,
        tensile_strength_weft_n=1002.0,
        air_permeability_cm3_per_s=151.0
    ),
    "FAB_SPEC_0112": YarnStructureSpec(
        fabric_id="FAB_SPEC_0112",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-112",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=172,
        picks_per_inch=127,
        weight_gsm=140.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=730.0,
        tensile_strength_weft_n=604.0,
        air_permeability_cm3_per_s=172.0
    ),
    "FAB_SPEC_0113": YarnStructureSpec(
        fabric_id="FAB_SPEC_0113",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-113",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=71,
        picks_per_inch=60,
        weight_gsm=188.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=802.5,
        tensile_strength_weft_n=706.0,
        air_permeability_cm3_per_s=343.0
    ),
    "FAB_SPEC_0114": YarnStructureSpec(
        fabric_id="FAB_SPEC_0114",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-114",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=134,
        picks_per_inch=104,
        weight_gsm=106.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=565.0,
        tensile_strength_weft_n=468.0,
        air_permeability_cm3_per_s=224.0
    ),
    "FAB_SPEC_0115": YarnStructureSpec(
        fabric_id="FAB_SPEC_0115",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-115",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=83,
        picks_per_inch=54,
        weight_gsm=515.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1537.5,
        tensile_strength_weft_n=1210.0,
        air_permeability_cm3_per_s=80.0
    ),
    "FAB_SPEC_0116": YarnStructureSpec(
        fabric_id="FAB_SPEC_0116",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-116",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=144,
        picks_per_inch=99,
        weight_gsm=216.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=910.0,
        tensile_strength_weft_n=772.0,
        air_permeability_cm3_per_s=246.0
    ),
    "FAB_SPEC_0117": YarnStructureSpec(
        fabric_id="FAB_SPEC_0117",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-117",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=157,
        picks_per_inch=122,
        weight_gsm=267.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=872.5,
        tensile_strength_weft_n=654.0,
        air_permeability_cm3_per_s=122.0
    ),
    "FAB_SPEC_0118": YarnStructureSpec(
        fabric_id="FAB_SPEC_0118",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-118",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=46,
        picks_per_inch=45,
        weight_gsm=248.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=505.0,
        tensile_strength_weft_n=426.0,
        air_permeability_cm3_per_s=418.0
    ),
    "FAB_SPEC_0119": YarnStructureSpec(
        fabric_id="FAB_SPEC_0119",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-119",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=61,
        picks_per_inch=52,
        weight_gsm=479.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1187.5,
        tensile_strength_weft_n=1018.0,
        air_permeability_cm3_per_s=159.0
    ),
    "FAB_SPEC_0120": YarnStructureSpec(
        fabric_id="FAB_SPEC_0120",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-120",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=160,
        picks_per_inch=120,
        weight_gsm=118.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=750.0,
        tensile_strength_weft_n=620.0,
        air_permeability_cm3_per_s=140.0
    ),
    "FAB_SPEC_0121": YarnStructureSpec(
        fabric_id="FAB_SPEC_0121",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-121",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=59,
        picks_per_inch=53,
        weight_gsm=166.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=822.5,
        tensile_strength_weft_n=722.0,
        air_permeability_cm3_per_s=311.0
    ),
    "FAB_SPEC_0122": YarnStructureSpec(
        fabric_id="FAB_SPEC_0122",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-122",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=122,
        picks_per_inch=97,
        weight_gsm=84.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=585.0,
        tensile_strength_weft_n=484.0,
        air_permeability_cm3_per_s=192.0
    ),
    "FAB_SPEC_0123": YarnStructureSpec(
        fabric_id="FAB_SPEC_0123",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-123",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=71,
        picks_per_inch=47,
        weight_gsm=493.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1557.5,
        tensile_strength_weft_n=1226.0,
        air_permeability_cm3_per_s=48.0
    ),
    "FAB_SPEC_0124": YarnStructureSpec(
        fabric_id="FAB_SPEC_0124",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-124",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=132,
        picks_per_inch=92,
        weight_gsm=194.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=930.0,
        tensile_strength_weft_n=788.0,
        air_permeability_cm3_per_s=214.0
    ),
    "FAB_SPEC_0125": YarnStructureSpec(
        fabric_id="FAB_SPEC_0125",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-125",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=145,
        picks_per_inch=115,
        weight_gsm=245.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=892.5,
        tensile_strength_weft_n=670.0,
        air_permeability_cm3_per_s=90.0
    ),
    "FAB_SPEC_0126": YarnStructureSpec(
        fabric_id="FAB_SPEC_0126",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-126",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=34,
        picks_per_inch=38,
        weight_gsm=226.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=525.0,
        tensile_strength_weft_n=442.0,
        air_permeability_cm3_per_s=386.0
    ),
    "FAB_SPEC_0127": YarnStructureSpec(
        fabric_id="FAB_SPEC_0127",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-127",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=49,
        picks_per_inch=45,
        weight_gsm=457.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1207.5,
        tensile_strength_weft_n=1034.0,
        air_permeability_cm3_per_s=127.0
    ),
    "FAB_SPEC_0128": YarnStructureSpec(
        fabric_id="FAB_SPEC_0128",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-128",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=168,
        picks_per_inch=128,
        weight_gsm=126.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=770.0,
        tensile_strength_weft_n=636.0,
        air_permeability_cm3_per_s=148.0
    ),
    "FAB_SPEC_0129": YarnStructureSpec(
        fabric_id="FAB_SPEC_0129",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-129",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=67,
        picks_per_inch=61,
        weight_gsm=174.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=842.5,
        tensile_strength_weft_n=738.0,
        air_permeability_cm3_per_s=319.0
    ),
    "FAB_SPEC_0130": YarnStructureSpec(
        fabric_id="FAB_SPEC_0130",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-130",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=130,
        picks_per_inch=105,
        weight_gsm=92.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=605.0,
        tensile_strength_weft_n=500.0,
        air_permeability_cm3_per_s=200.0
    ),
    "FAB_SPEC_0131": YarnStructureSpec(
        fabric_id="FAB_SPEC_0131",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-131",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=79,
        picks_per_inch=55,
        weight_gsm=501.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1577.5,
        tensile_strength_weft_n=1242.0,
        air_permeability_cm3_per_s=56.0
    ),
    "FAB_SPEC_0132": YarnStructureSpec(
        fabric_id="FAB_SPEC_0132",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-132",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=140,
        picks_per_inch=100,
        weight_gsm=202.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=950.0,
        tensile_strength_weft_n=804.0,
        air_permeability_cm3_per_s=222.0
    ),
    "FAB_SPEC_0133": YarnStructureSpec(
        fabric_id="FAB_SPEC_0133",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-133",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=153,
        picks_per_inch=123,
        weight_gsm=253.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=912.5,
        tensile_strength_weft_n=686.0,
        air_permeability_cm3_per_s=98.0
    ),
    "FAB_SPEC_0134": YarnStructureSpec(
        fabric_id="FAB_SPEC_0134",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-134",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=42,
        picks_per_inch=46,
        weight_gsm=234.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=545.0,
        tensile_strength_weft_n=458.0,
        air_permeability_cm3_per_s=394.0
    ),
    "FAB_SPEC_0135": YarnStructureSpec(
        fabric_id="FAB_SPEC_0135",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-135",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=57,
        picks_per_inch=38,
        weight_gsm=465.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1227.5,
        tensile_strength_weft_n=1050.0,
        air_permeability_cm3_per_s=135.0
    ),
    "FAB_SPEC_0136": YarnStructureSpec(
        fabric_id="FAB_SPEC_0136",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-136",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=176,
        picks_per_inch=121,
        weight_gsm=134.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=790.0,
        tensile_strength_weft_n=652.0,
        air_permeability_cm3_per_s=156.0
    ),
    "FAB_SPEC_0137": YarnStructureSpec(
        fabric_id="FAB_SPEC_0137",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-137",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=75,
        picks_per_inch=54,
        weight_gsm=182.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=862.5,
        tensile_strength_weft_n=754.0,
        air_permeability_cm3_per_s=327.0
    ),
    "FAB_SPEC_0138": YarnStructureSpec(
        fabric_id="FAB_SPEC_0138",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-138",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=138,
        picks_per_inch=98,
        weight_gsm=100.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=625.0,
        tensile_strength_weft_n=516.0,
        air_permeability_cm3_per_s=208.0
    ),
    "FAB_SPEC_0139": YarnStructureSpec(
        fabric_id="FAB_SPEC_0139",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-139",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=87,
        picks_per_inch=48,
        weight_gsm=509.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1597.5,
        tensile_strength_weft_n=1258.0,
        air_permeability_cm3_per_s=64.0
    ),
    "FAB_SPEC_0140": YarnStructureSpec(
        fabric_id="FAB_SPEC_0140",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-140",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=128,
        picks_per_inch=93,
        weight_gsm=210.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=970.0,
        tensile_strength_weft_n=820.0,
        air_permeability_cm3_per_s=230.0
    ),
    "FAB_SPEC_0141": YarnStructureSpec(
        fabric_id="FAB_SPEC_0141",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-141",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=141,
        picks_per_inch=116,
        weight_gsm=261.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=932.5,
        tensile_strength_weft_n=702.0,
        air_permeability_cm3_per_s=106.0
    ),
    "FAB_SPEC_0142": YarnStructureSpec(
        fabric_id="FAB_SPEC_0142",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-142",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=30,
        picks_per_inch=39,
        weight_gsm=242.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=565.0,
        tensile_strength_weft_n=474.0,
        air_permeability_cm3_per_s=402.0
    ),
    "FAB_SPEC_0143": YarnStructureSpec(
        fabric_id="FAB_SPEC_0143",
        commercial_trade_name="Heavyweight Organic Loopback French Terry Grade-143",
        fiber_blend_ratio="100% Combed Organic Cotton",
        warp_yarn_count="30s Face / 10s Loop",
        weft_yarn_count="10s Carded Loop",
        ends_per_inch=45,
        picks_per_inch=46,
        weight_gsm=473.0,
        finishing_processes=['Siliconized Soft Wash', 'Anti-Pilling Bio-Polishing'],
        tensile_strength_warp_n=1247.5,
        tensile_strength_weft_n=1066.0,
        air_permeability_cm3_per_s=143.0
    ),
    "FAB_SPEC_0144": YarnStructureSpec(
        fabric_id="FAB_SPEC_0144",
        commercial_trade_name="Giza 88 Extra-Long Staple Cotton Poplin 120/2 Grade-144",
        fiber_blend_ratio="100% Giza Cotton",
        warp_yarn_count="120/2 Ne Compact",
        weft_yarn_count="120/2 Ne Compact",
        ends_per_inch=164,
        picks_per_inch=129,
        weight_gsm=142.0,
        finishing_processes=['Liquid Ammonia Finish', 'Soft Mercerization', 'Sanforized Preshrunk'],
        tensile_strength_warp_n=810.0,
        tensile_strength_weft_n=668.0,
        air_permeability_cm3_per_s=164.0
    ),
    "FAB_SPEC_0145": YarnStructureSpec(
        fabric_id="FAB_SPEC_0145",
        commercial_trade_name="Belgian Wet-Spun Pure Flax Linen Plain Grade-145",
        fiber_blend_ratio="100% Flax Linen",
        warp_yarn_count="36 Lea Wet Spun",
        weft_yarn_count="36 Lea Wet Spun",
        ends_per_inch=63,
        picks_per_inch=62,
        weight_gsm=190.0,
        finishing_processes=['Bio-Enzyme Stone Wash', 'Natural Air Tumbling'],
        tensile_strength_warp_n=882.5,
        tensile_strength_weft_n=770.0,
        air_permeability_cm3_per_s=335.0
    ),
    "FAB_SPEC_0146": YarnStructureSpec(
        fabric_id="FAB_SPEC_0146",
        commercial_trade_name="Grade 6A Mulberry Silk Satin Charmeuse 19mm Grade-146",
        fiber_blend_ratio="100% Mulberry Silk",
        warp_yarn_count="20/22 Denier Raw Silk",
        weft_yarn_count="20/22 Denier Crepe Twist",
        ends_per_inch=126,
        picks_per_inch=106,
        weight_gsm=108.0,
        finishing_processes=['Sand Washed Matte Finish', 'Degummed Silk Luster'],
        tensile_strength_warp_n=645.0,
        tensile_strength_weft_n=532.0,
        air_permeability_cm3_per_s=216.0
    ),
    "FAB_SPEC_0147": YarnStructureSpec(
        fabric_id="FAB_SPEC_0147",
        commercial_trade_name="Kuroki Okayama Redline Raw Selvedge Denim 14.5oz Grade-147",
        fiber_blend_ratio="100% Cotton",
        warp_yarn_count="7s Ring Spun Rope Dyed",
        weft_yarn_count="6s Slub Weft",
        ends_per_inch=75,
        picks_per_inch=56,
        weight_gsm=517.0,
        finishing_processes=['Raw Loomstate Untreated', 'Starch Stiffened'],
        tensile_strength_warp_n=1617.5,
        tensile_strength_weft_n=1274.0,
        air_permeability_cm3_per_s=72.0
    ),
    "FAB_SPEC_0148": YarnStructureSpec(
        fabric_id="FAB_SPEC_0148",
        commercial_trade_name="Lenzing MicroModal TENCEL™ Twill 2/1 Grade-148",
        fiber_blend_ratio="100% Lyocell",
        warp_yarn_count="40s Lyocell Compact",
        weft_yarn_count="40s Lyocell Compact",
        ends_per_inch=136,
        picks_per_inch=101,
        weight_gsm=218.0,
        finishing_processes=['Eco Soft Flow Dyeing', 'Fibrillation Control Treatment'],
        tensile_strength_warp_n=990.0,
        tensile_strength_weft_n=836.0,
        air_permeability_cm3_per_s=238.0
    ),
    "FAB_SPEC_0149": YarnStructureSpec(
        fabric_id="FAB_SPEC_0149",
        commercial_trade_name="Katan Silk Zari Royal Brocade 240 GSM Grade-149",
        fiber_blend_ratio="82% Katan Silk, 18% Metallic Zari",
        warp_yarn_count="20/22D Multi-Filament",
        weft_yarn_count="Real Silver Gilt Badla",
        ends_per_inch=149,
        picks_per_inch=124,
        weight_gsm=269.0,
        finishing_processes=['Traditional Handloom Jacquard Loomstate'],
        tensile_strength_warp_n=952.5,
        tensile_strength_weft_n=718.0,
        air_permeability_cm3_per_s=114.0
    ),
    "FAB_SPEC_0150": YarnStructureSpec(
        fabric_id="FAB_SPEC_0150",
        commercial_trade_name="Grade-A Mongolian Cashmere Jersey 2/28Nm Grade-150",
        fiber_blend_ratio="100% Cashmere",
        warp_yarn_count="2/28 Nm Woollen Spun",
        weft_yarn_count="2/28 Nm Woollen Spun",
        ends_per_inch=38,
        picks_per_inch=32,
        weight_gsm=220.0,
        finishing_processes=['Mountain Spring Water Milling', 'Natural Teasel Raising'],
        tensile_strength_warp_n=585.0,
        tensile_strength_weft_n=490.0,
        air_permeability_cm3_per_s=410.0
    ),
}
