"""
Fine Jewelry, Precious Metals, Gemstones & Luxury Leather Goods Taxonomy.
Defines precious metal karatage purity (24K, 22K, 18K, 14K, 925 Silver),
gemstone setting classifications (Polki, Kundan, Jadau, Pavé), and leather grain grades.
"""

from typing import Dict, List, Optional, Any
from pydantic import BaseModel

class AccessoryCraftProfile(BaseModel):
    item_code: str
    trade_name: str
    category: str
    base_material: str
    purity_specification: str
    setting_technique: str
    hallmark_certification_standard: str
    care_guidelines: List[str]
    formality_tier: int

ACCESSORY_CRAFT_DATABASE: Dict[str, AccessoryCraftProfile] = {
    "ACC_SPEC_0001": AccessoryCraftProfile(
        item_code="ACC_SPEC_0001",
        trade_name="Six-Prong Platinum Solitaire Ring Series-1",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0002": AccessoryCraftProfile(
        item_code="ACC_SPEC_0002",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-2",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0003": AccessoryCraftProfile(
        item_code="ACC_SPEC_0003",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-3",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0004": AccessoryCraftProfile(
        item_code="ACC_SPEC_0004",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-4",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0005": AccessoryCraftProfile(
        item_code="ACC_SPEC_0005",
        trade_name="Heritage Royal Jadau Polki Choker Series-5",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0006": AccessoryCraftProfile(
        item_code="ACC_SPEC_0006",
        trade_name="Six-Prong Platinum Solitaire Ring Series-6",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0007": AccessoryCraftProfile(
        item_code="ACC_SPEC_0007",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-7",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0008": AccessoryCraftProfile(
        item_code="ACC_SPEC_0008",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-8",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0009": AccessoryCraftProfile(
        item_code="ACC_SPEC_0009",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-9",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0010": AccessoryCraftProfile(
        item_code="ACC_SPEC_0010",
        trade_name="Heritage Royal Jadau Polki Choker Series-10",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0011": AccessoryCraftProfile(
        item_code="ACC_SPEC_0011",
        trade_name="Six-Prong Platinum Solitaire Ring Series-11",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0012": AccessoryCraftProfile(
        item_code="ACC_SPEC_0012",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-12",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0013": AccessoryCraftProfile(
        item_code="ACC_SPEC_0013",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-13",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0014": AccessoryCraftProfile(
        item_code="ACC_SPEC_0014",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-14",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0015": AccessoryCraftProfile(
        item_code="ACC_SPEC_0015",
        trade_name="Heritage Royal Jadau Polki Choker Series-15",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0016": AccessoryCraftProfile(
        item_code="ACC_SPEC_0016",
        trade_name="Six-Prong Platinum Solitaire Ring Series-16",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0017": AccessoryCraftProfile(
        item_code="ACC_SPEC_0017",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-17",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0018": AccessoryCraftProfile(
        item_code="ACC_SPEC_0018",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-18",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0019": AccessoryCraftProfile(
        item_code="ACC_SPEC_0019",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-19",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0020": AccessoryCraftProfile(
        item_code="ACC_SPEC_0020",
        trade_name="Heritage Royal Jadau Polki Choker Series-20",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0021": AccessoryCraftProfile(
        item_code="ACC_SPEC_0021",
        trade_name="Six-Prong Platinum Solitaire Ring Series-21",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0022": AccessoryCraftProfile(
        item_code="ACC_SPEC_0022",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-22",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0023": AccessoryCraftProfile(
        item_code="ACC_SPEC_0023",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-23",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0024": AccessoryCraftProfile(
        item_code="ACC_SPEC_0024",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-24",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0025": AccessoryCraftProfile(
        item_code="ACC_SPEC_0025",
        trade_name="Heritage Royal Jadau Polki Choker Series-25",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0026": AccessoryCraftProfile(
        item_code="ACC_SPEC_0026",
        trade_name="Six-Prong Platinum Solitaire Ring Series-26",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0027": AccessoryCraftProfile(
        item_code="ACC_SPEC_0027",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-27",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0028": AccessoryCraftProfile(
        item_code="ACC_SPEC_0028",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-28",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0029": AccessoryCraftProfile(
        item_code="ACC_SPEC_0029",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-29",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0030": AccessoryCraftProfile(
        item_code="ACC_SPEC_0030",
        trade_name="Heritage Royal Jadau Polki Choker Series-30",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0031": AccessoryCraftProfile(
        item_code="ACC_SPEC_0031",
        trade_name="Six-Prong Platinum Solitaire Ring Series-31",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0032": AccessoryCraftProfile(
        item_code="ACC_SPEC_0032",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-32",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0033": AccessoryCraftProfile(
        item_code="ACC_SPEC_0033",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-33",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0034": AccessoryCraftProfile(
        item_code="ACC_SPEC_0034",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-34",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0035": AccessoryCraftProfile(
        item_code="ACC_SPEC_0035",
        trade_name="Heritage Royal Jadau Polki Choker Series-35",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0036": AccessoryCraftProfile(
        item_code="ACC_SPEC_0036",
        trade_name="Six-Prong Platinum Solitaire Ring Series-36",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0037": AccessoryCraftProfile(
        item_code="ACC_SPEC_0037",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-37",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0038": AccessoryCraftProfile(
        item_code="ACC_SPEC_0038",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-38",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0039": AccessoryCraftProfile(
        item_code="ACC_SPEC_0039",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-39",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0040": AccessoryCraftProfile(
        item_code="ACC_SPEC_0040",
        trade_name="Heritage Royal Jadau Polki Choker Series-40",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0041": AccessoryCraftProfile(
        item_code="ACC_SPEC_0041",
        trade_name="Six-Prong Platinum Solitaire Ring Series-41",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0042": AccessoryCraftProfile(
        item_code="ACC_SPEC_0042",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-42",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0043": AccessoryCraftProfile(
        item_code="ACC_SPEC_0043",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-43",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0044": AccessoryCraftProfile(
        item_code="ACC_SPEC_0044",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-44",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0045": AccessoryCraftProfile(
        item_code="ACC_SPEC_0045",
        trade_name="Heritage Royal Jadau Polki Choker Series-45",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0046": AccessoryCraftProfile(
        item_code="ACC_SPEC_0046",
        trade_name="Six-Prong Platinum Solitaire Ring Series-46",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0047": AccessoryCraftProfile(
        item_code="ACC_SPEC_0047",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-47",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0048": AccessoryCraftProfile(
        item_code="ACC_SPEC_0048",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-48",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0049": AccessoryCraftProfile(
        item_code="ACC_SPEC_0049",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-49",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0050": AccessoryCraftProfile(
        item_code="ACC_SPEC_0050",
        trade_name="Heritage Royal Jadau Polki Choker Series-50",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0051": AccessoryCraftProfile(
        item_code="ACC_SPEC_0051",
        trade_name="Six-Prong Platinum Solitaire Ring Series-51",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0052": AccessoryCraftProfile(
        item_code="ACC_SPEC_0052",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-52",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0053": AccessoryCraftProfile(
        item_code="ACC_SPEC_0053",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-53",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0054": AccessoryCraftProfile(
        item_code="ACC_SPEC_0054",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-54",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0055": AccessoryCraftProfile(
        item_code="ACC_SPEC_0055",
        trade_name="Heritage Royal Jadau Polki Choker Series-55",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0056": AccessoryCraftProfile(
        item_code="ACC_SPEC_0056",
        trade_name="Six-Prong Platinum Solitaire Ring Series-56",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0057": AccessoryCraftProfile(
        item_code="ACC_SPEC_0057",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-57",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0058": AccessoryCraftProfile(
        item_code="ACC_SPEC_0058",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-58",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0059": AccessoryCraftProfile(
        item_code="ACC_SPEC_0059",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-59",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0060": AccessoryCraftProfile(
        item_code="ACC_SPEC_0060",
        trade_name="Heritage Royal Jadau Polki Choker Series-60",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0061": AccessoryCraftProfile(
        item_code="ACC_SPEC_0061",
        trade_name="Six-Prong Platinum Solitaire Ring Series-61",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0062": AccessoryCraftProfile(
        item_code="ACC_SPEC_0062",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-62",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0063": AccessoryCraftProfile(
        item_code="ACC_SPEC_0063",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-63",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0064": AccessoryCraftProfile(
        item_code="ACC_SPEC_0064",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-64",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0065": AccessoryCraftProfile(
        item_code="ACC_SPEC_0065",
        trade_name="Heritage Royal Jadau Polki Choker Series-65",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0066": AccessoryCraftProfile(
        item_code="ACC_SPEC_0066",
        trade_name="Six-Prong Platinum Solitaire Ring Series-66",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0067": AccessoryCraftProfile(
        item_code="ACC_SPEC_0067",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-67",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0068": AccessoryCraftProfile(
        item_code="ACC_SPEC_0068",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-68",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0069": AccessoryCraftProfile(
        item_code="ACC_SPEC_0069",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-69",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0070": AccessoryCraftProfile(
        item_code="ACC_SPEC_0070",
        trade_name="Heritage Royal Jadau Polki Choker Series-70",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0071": AccessoryCraftProfile(
        item_code="ACC_SPEC_0071",
        trade_name="Six-Prong Platinum Solitaire Ring Series-71",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0072": AccessoryCraftProfile(
        item_code="ACC_SPEC_0072",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-72",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0073": AccessoryCraftProfile(
        item_code="ACC_SPEC_0073",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-73",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0074": AccessoryCraftProfile(
        item_code="ACC_SPEC_0074",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-74",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0075": AccessoryCraftProfile(
        item_code="ACC_SPEC_0075",
        trade_name="Heritage Royal Jadau Polki Choker Series-75",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0076": AccessoryCraftProfile(
        item_code="ACC_SPEC_0076",
        trade_name="Six-Prong Platinum Solitaire Ring Series-76",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0077": AccessoryCraftProfile(
        item_code="ACC_SPEC_0077",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-77",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0078": AccessoryCraftProfile(
        item_code="ACC_SPEC_0078",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-78",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0079": AccessoryCraftProfile(
        item_code="ACC_SPEC_0079",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-79",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0080": AccessoryCraftProfile(
        item_code="ACC_SPEC_0080",
        trade_name="Heritage Royal Jadau Polki Choker Series-80",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0081": AccessoryCraftProfile(
        item_code="ACC_SPEC_0081",
        trade_name="Six-Prong Platinum Solitaire Ring Series-81",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0082": AccessoryCraftProfile(
        item_code="ACC_SPEC_0082",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-82",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0083": AccessoryCraftProfile(
        item_code="ACC_SPEC_0083",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-83",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0084": AccessoryCraftProfile(
        item_code="ACC_SPEC_0084",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-84",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0085": AccessoryCraftProfile(
        item_code="ACC_SPEC_0085",
        trade_name="Heritage Royal Jadau Polki Choker Series-85",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0086": AccessoryCraftProfile(
        item_code="ACC_SPEC_0086",
        trade_name="Six-Prong Platinum Solitaire Ring Series-86",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0087": AccessoryCraftProfile(
        item_code="ACC_SPEC_0087",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-87",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0088": AccessoryCraftProfile(
        item_code="ACC_SPEC_0088",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-88",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0089": AccessoryCraftProfile(
        item_code="ACC_SPEC_0089",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-89",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0090": AccessoryCraftProfile(
        item_code="ACC_SPEC_0090",
        trade_name="Heritage Royal Jadau Polki Choker Series-90",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0091": AccessoryCraftProfile(
        item_code="ACC_SPEC_0091",
        trade_name="Six-Prong Platinum Solitaire Ring Series-91",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0092": AccessoryCraftProfile(
        item_code="ACC_SPEC_0092",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-92",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0093": AccessoryCraftProfile(
        item_code="ACC_SPEC_0093",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-93",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0094": AccessoryCraftProfile(
        item_code="ACC_SPEC_0094",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-94",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0095": AccessoryCraftProfile(
        item_code="ACC_SPEC_0095",
        trade_name="Heritage Royal Jadau Polki Choker Series-95",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
    "ACC_SPEC_0096": AccessoryCraftProfile(
        item_code="ACC_SPEC_0096",
        trade_name="Six-Prong Platinum Solitaire Ring Series-96",
        category="FINE_JEWELRY",
        base_material="Platinum 950",
        purity_specification="95.0% Pure Platinum",
        setting_technique="Six-Prong Classic Wire Setting",
        hallmark_certification_standard="GIA Certified Laser Inscribed",
        care_guidelines=['Ultrasonic clean safe', 'Store separately to prevent scratching other metals'],
        formality_tier=5
    ),
    "ACC_SPEC_0097": AccessoryCraftProfile(
        item_code="ACC_SPEC_0097",
        trade_name="Architectural Grade-5 Titanium Chronograph Series-97",
        category="HOROLOGY",
        base_material="Titanium Grade 5",
        purity_specification="Alpha-Beta Titanium Alloy",
        setting_technique="Integrated Ceramic Bezel with Sapphire Crystal",
        hallmark_certification_standard="Swiss Made ISO 1413 Shock Resistance",
        care_guidelines=['100m water resistant', 'Rinse with freshwater after saltwater exposure'],
        formality_tier=3
    ),
    "ACC_SPEC_0098": AccessoryCraftProfile(
        item_code="ACC_SPEC_0098",
        trade_name="Hand-Stitched Full-Grain Saddle Leather Tote Series-98",
        category="LEATHER_GOODS",
        base_material="French Full-Grain Taurillon Leather",
        purity_specification="Aniline Tanned Vegetable Grain",
        setting_technique="Double Saddle Stitching with Waxed Linen Thread",
        hallmark_certification_standard="Artisanal Certificate of Authenticity",
        care_guidelines=['Condition with beeswax leather balm twice yearly', 'Keep away from prolonged direct heat'],
        formality_tier=3
    ),
    "ACC_SPEC_0099": AccessoryCraftProfile(
        item_code="ACC_SPEC_0099",
        trade_name="Hand-Rolled 16-Momme Silk Twill Pocket Square Series-99",
        category="TEXTILE_ACCESSORY",
        base_material="100% Mulberry Silk Twill",
        purity_specification="High-Twist 16mm Weight",
        setting_technique="Hand-Rolled and Hand-Sewn Tubular Hem",
        hallmark_certification_standard="Silk Mark Certified",
        care_guidelines=['Dry clean only', 'Press with low steam on reverse side'],
        formality_tier=4
    ),
    "ACC_SPEC_0100": AccessoryCraftProfile(
        item_code="ACC_SPEC_0100",
        trade_name="Heritage Royal Jadau Polki Choker Series-100",
        category="HIGH_JEWELRY",
        base_material="22 Karat Yellow Gold",
        purity_specification="91.6% Pure Gold with Pure Silver Foil Underlay",
        setting_technique="Traditional Jadau Bezel Setting",
        hallmark_certification_standard="BIS Hallmark 916",
        care_guidelines=['Clean only with dry microfibre cloth', 'Never expose to liquid jewelry cleaners', 'Store in velvet-lined wooden box'],
        formality_tier=5
    ),
}
