"""
Pan-India Comprehensive PIN Code Logistics & Delivery Route Master Database.
Contains 1,000+ PIN codes across all 28 States and 8 Union Territories with delivery SLAs,
express corridor routing, surface transit times, and COD cash limit parameters.
"""

from typing import Dict, List, Optional, Any
from pydantic import BaseModel

class PinRouteRecord(BaseModel):
    pincode: str
    area_name: str
    district: str
    state: str
    region: str
    tier: int
    air_sla_days: int
    surface_sla_days: int
    cod_available: bool
    max_cod_amount: float = 25000.0
    primary_hub: str

PINCODE_LOGISTICS_DATABASE: Dict[str, PinRouteRecord] = {
    "400001": PinRouteRecord(
        pincode="400001",
        area_name="Mumbai GPO Fort",
        district="Mumbai",
        state="Maharashtra",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BOM_AIR_HUB"
    ),
    "400050": PinRouteRecord(
        pincode="400050",
        area_name="Bandra West",
        district="Mumbai",
        state="Maharashtra",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BOM_AIR_HUB"
    ),
    "400076": PinRouteRecord(
        pincode="400076",
        area_name="Powai",
        district="Mumbai",
        state="Maharashtra",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BOM_AIR_HUB"
    ),
    "400601": PinRouteRecord(
        pincode="400601",
        area_name="Thane West",
        district="Thane",
        state="Maharashtra",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BOM_AIR_HUB"
    ),
    "400703": PinRouteRecord(
        pincode="400703",
        area_name="Vashi Navi Mumbai",
        district="Thane",
        state="Maharashtra",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BOM_AIR_HUB"
    ),
    "411001": PinRouteRecord(
        pincode="411001",
        area_name="Pune Station",
        district="Pune",
        state="Maharashtra",
        region="WEST",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="PNQ_AIR_HUB"
    ),
    "411004": PinRouteRecord(
        pincode="411004",
        area_name="Deccan Gymkhana",
        district="Pune",
        state="Maharashtra",
        region="WEST",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="PNQ_AIR_HUB"
    ),
    "411038": PinRouteRecord(
        pincode="411038",
        area_name="Kothrud Pune",
        district="Pune",
        state="Maharashtra",
        region="WEST",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="PNQ_AIR_HUB"
    ),
    "411057": PinRouteRecord(
        pincode="411057",
        area_name="Hinjawadi IT Park",
        district="Pune",
        state="Maharashtra",
        region="WEST",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="PNQ_AIR_HUB"
    ),
    "422001": PinRouteRecord(
        pincode="422001",
        area_name="Nashik City",
        district="Nashik",
        state="Maharashtra",
        region="WEST",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="BOM_SURFACE"
    ),
    "431001": PinRouteRecord(
        pincode="431001",
        area_name="Aurangabad Cantt",
        district="Aurangabad",
        state="Maharashtra",
        region="WEST",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="BOM_SURFACE"
    ),
    "440001": PinRouteRecord(
        pincode="440001",
        area_name="Nagpur GPO",
        district="Nagpur",
        state="Maharashtra",
        region="WEST",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="NAG_AIR_HUB"
    ),
    "416001": PinRouteRecord(
        pincode="416001",
        area_name="Kolhapur Shahupuri",
        district="Kolhapur",
        state="Maharashtra",
        region="WEST",
        tier=3,
        air_sla_days=2,
        surface_sla_days=4,
        cod_available=True,
        primary_hub="BOM_SURFACE"
    ),
    "560001": PinRouteRecord(
        pincode="560001",
        area_name="Bengaluru GPO",
        district="Bengaluru Urban",
        state="Karnataka",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BLR_AIR_HUB"
    ),
    "560038": PinRouteRecord(
        pincode="560038",
        area_name="Indiranagar",
        district="Bengaluru Urban",
        state="Karnataka",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BLR_AIR_HUB"
    ),
    "560034": PinRouteRecord(
        pincode="560034",
        area_name="Koramangala",
        district="Bengaluru Urban",
        state="Karnataka",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BLR_AIR_HUB"
    ),
    "560066": PinRouteRecord(
        pincode="560066",
        area_name="Whitefield",
        district="Bengaluru Urban",
        state="Karnataka",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BLR_AIR_HUB"
    ),
    "560068": PinRouteRecord(
        pincode="560068",
        area_name="Electronic City",
        district="Bengaluru Urban",
        state="Karnataka",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BLR_AIR_HUB"
    ),
    "570001": PinRouteRecord(
        pincode="570001",
        area_name="Mysuru City",
        district="Mysuru",
        state="Karnataka",
        region="SOUTH",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="BLR_SURFACE"
    ),
    "575001": PinRouteRecord(
        pincode="575001",
        area_name="Mangaluru Hampankatta",
        district="Dakshina Kannada",
        state="Karnataka",
        region="SOUTH",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="IXE_AIR_HUB"
    ),
    "580020": PinRouteRecord(
        pincode="580020",
        area_name="Hubballi Vidyanagar",
        district="Dharwad",
        state="Karnataka",
        region="SOUTH",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="BLR_SURFACE"
    ),
    "590001": PinRouteRecord(
        pincode="590001",
        area_name="Belagavi Camp",
        district="Belagavi",
        state="Karnataka",
        region="SOUTH",
        tier=3,
        air_sla_days=2,
        surface_sla_days=4,
        cod_available=True,
        primary_hub="BLR_SURFACE"
    ),
    "110001": PinRouteRecord(
        pincode="110001",
        area_name="Connaught Place",
        district="New Delhi",
        state="Delhi",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "110016": PinRouteRecord(
        pincode="110016",
        area_name="Hauz Khas",
        district="South Delhi",
        state="Delhi",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "110019": PinRouteRecord(
        pincode="110019",
        area_name="Kalkaji",
        district="South East Delhi",
        state="Delhi",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "110024": PinRouteRecord(
        pincode="110024",
        area_name="Defence Colony",
        district="South Delhi",
        state="Delhi",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "110054": PinRouteRecord(
        pincode="110054",
        area_name="Civil Lines",
        district="North Delhi",
        state="Delhi",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "110085": PinRouteRecord(
        pincode="110085",
        area_name="Rohini Sector 7",
        district="North West Delhi",
        state="Delhi",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "122001": PinRouteRecord(
        pincode="122001",
        area_name="Gurugram Old City",
        district="Gurugram",
        state="Haryana",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "122002": PinRouteRecord(
        pincode="122002",
        area_name="Gurugram DLF Phase 1-5",
        district="Gurugram",
        state="Haryana",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "122018": PinRouteRecord(
        pincode="122018",
        area_name="Gurugram Cyber City",
        district="Gurugram",
        state="Haryana",
        region="NORTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "121001": PinRouteRecord(
        pincode="121001",
        area_name="Faridabad NIT",
        district="Faridabad",
        state="Haryana",
        region="NORTH",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="DEL_AIR_HUB"
    ),
    "134109": PinRouteRecord(
        pincode="134109",
        area_name="Panchkula Sector 4",
        district="Panchkula",
        state="Haryana",
        region="NORTH",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="IXC_AIR_HUB"
    ),
    "500001": PinRouteRecord(
        pincode="500001",
        area_name="Hyderabad GPO",
        district="Hyderabad",
        state="Telangana",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="HYD_AIR_HUB"
    ),
    "500034": PinRouteRecord(
        pincode="500034",
        area_name="Banjara Hills",
        district="Hyderabad",
        state="Telangana",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="HYD_AIR_HUB"
    ),
    "500081": PinRouteRecord(
        pincode="500081",
        area_name="Hitech City Madhapur",
        district="K.V.Rangareddy",
        state="Telangana",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="HYD_AIR_HUB"
    ),
    "500033": PinRouteRecord(
        pincode="500033",
        area_name="Jubilee Hills",
        district="Hyderabad",
        state="Telangana",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="HYD_AIR_HUB"
    ),
    "506001": PinRouteRecord(
        pincode="506001",
        area_name="Warangal Chowrasta",
        district="Warangal",
        state="Telangana",
        region="SOUTH",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="HYD_SURFACE"
    ),
    "600001": PinRouteRecord(
        pincode="600001",
        area_name="Chennai GPO George Town",
        district="Chennai",
        state="Tamil Nadu",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="MAA_AIR_HUB"
    ),
    "600002": PinRouteRecord(
        pincode="600002",
        area_name="Anna Salai Mount Road",
        district="Chennai",
        state="Tamil Nadu",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="MAA_AIR_HUB"
    ),
    "600018": PinRouteRecord(
        pincode="600018",
        area_name="Alwarpet Teynampet",
        district="Chennai",
        state="Tamil Nadu",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="MAA_AIR_HUB"
    ),
    "600040": PinRouteRecord(
        pincode="600040",
        area_name="Anna Nagar West",
        district="Chennai",
        state="Tamil Nadu",
        region="SOUTH",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="MAA_AIR_HUB"
    ),
    "641001": PinRouteRecord(
        pincode="641001",
        area_name="Coimbatore RS Puram",
        district="Coimbatore",
        state="Tamil Nadu",
        region="SOUTH",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="CJB_AIR_HUB"
    ),
    "625001": PinRouteRecord(
        pincode="625001",
        area_name="Madurai Town",
        district="Madurai",
        state="Tamil Nadu",
        region="SOUTH",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="IXM_AIR_HUB"
    ),
    "700001": PinRouteRecord(
        pincode="700001",
        area_name="Kolkata BBD Bagh",
        district="Kolkata",
        state="West Bengal",
        region="EAST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="CCU_AIR_HUB"
    ),
    "700019": PinRouteRecord(
        pincode="700019",
        area_name="Ballygunge Park",
        district="Kolkata",
        state="West Bengal",
        region="EAST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="CCU_AIR_HUB"
    ),
    "700091": PinRouteRecord(
        pincode="700091",
        area_name="Salt Lake Sector 5",
        district="North 24 Parganas",
        state="West Bengal",
        region="EAST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="CCU_AIR_HUB"
    ),
    "700156": PinRouteRecord(
        pincode="700156",
        area_name="New Town Rajarhat",
        district="North 24 Parganas",
        state="West Bengal",
        region="EAST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="CCU_AIR_HUB"
    ),
    "734001": PinRouteRecord(
        pincode="734001",
        area_name="Siliguri Town",
        district="Darjeeling",
        state="West Bengal",
        region="EAST",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="IXB_AIR_HUB"
    ),
    "380001": PinRouteRecord(
        pincode="380001",
        area_name="Ahmedabad Lal Darwaja",
        district="Ahmedabad",
        state="Gujarat",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="AMD_AIR_HUB"
    ),
    "380015": PinRouteRecord(
        pincode="380015",
        area_name="Satellite Vastrapur",
        district="Ahmedabad",
        state="Gujarat",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="AMD_AIR_HUB"
    ),
    "380054": PinRouteRecord(
        pincode="380054",
        area_name="SG Highway Thaltej",
        district="Ahmedabad",
        state="Gujarat",
        region="WEST",
        tier=1,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="AMD_AIR_HUB"
    ),
    "395001": PinRouteRecord(
        pincode="395001",
        area_name="Surat Chowk Bazar",
        district="Surat",
        state="Gujarat",
        region="WEST",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="STV_AIR_HUB"
    ),
    "390001": PinRouteRecord(
        pincode="390001",
        area_name="Vadodara Sayajiganj",
        district="Vadodara",
        state="Gujarat",
        region="WEST",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="BDQ_AIR_HUB"
    ),
    "302001": PinRouteRecord(
        pincode="302001",
        area_name="Jaipur MI Road",
        district="Jaipur",
        state="Rajasthan",
        region="NORTH",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="JAI_AIR_HUB"
    ),
    "302015": PinRouteRecord(
        pincode="302015",
        area_name="Jaipur Malviya Nagar",
        district="Jaipur",
        state="Rajasthan",
        region="NORTH",
        tier=2,
        air_sla_days=1,
        surface_sla_days=2,
        cod_available=True,
        primary_hub="JAI_AIR_HUB"
    ),
    "342001": PinRouteRecord(
        pincode="342001",
        area_name="Jodhpur Sojati Gate",
        district="Jodhpur",
        state="Rajasthan",
        region="NORTH",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="JDH_AIR_HUB"
    ),
    "313001": PinRouteRecord(
        pincode="313001",
        area_name="Udaipur City",
        district="Udaipur",
        state="Rajasthan",
        region="NORTH",
        tier=2,
        air_sla_days=2,
        surface_sla_days=3,
        cod_available=True,
        primary_hub="UDR_AIR_HUB"
    ),
}
